version: 0.1

phases:
  install:
    commands:
      - npm install 
  build:
    commands:
      - npm test -- ci filter='addS3EventSource' | tee buildresult.txt 

artifacts:
  files:
    - buildresult.txt
  discard-paths: yes
